name: check_dataset
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]

jobs:
  ancientMetagenomeDirCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/SPAAM-workshop/AncientMetagenomeDirCheck.git
      - name: test ancient host-associatd metagenome (e.g. microbiomes)
        run: ancientMetagenomeDirCheck ancientmetagenome-hostassociated/ancientmetagenome-hostassociated.tsv ancientmetagenome-hostassociated/ancientmetagenome-hostassociated_schema.json
      - name: test ancient single microbial genomes (e.g. pathogens)
        run: ancientMetagenomeDirCheck ancientsinglegenome-hostassociated/ancientsinglegenome-hostassociated.tsv ancientsinglegenome-hostassociated/ancientsinglegenome-hostassociated_schema.json
      - name: test ancient environmental (e.g. sediment)
        run: ancientMetagenomeDirCheck ancientmetagenome-environmental/ancientmetagenome-environmental.tsv ancientmetagenome-environmental/ancientmetagenome-environmental_schema.json
              
